#!/bin/bash
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_awsv/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_bridge/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_rbss/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_clf/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed1/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed2/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed3/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed4/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed5/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed6/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed7/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed8/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed9/*.gz
rm -f  /opt/data/stage01/PT/data/dr_simulation/td_feed10/*.gz



