#!/bin/bash
dfn=$(printf "%s_%s" "tokilltmp" "$(date +%m%d%H%M%S)")

ps -ef | grep collect_eugene* | grep -v grep | awk '{print $2}' >> ./logs/test/$dfn

while read line
do
kill -9 $line
echo $line
done < ./logs/test/$dfn

rm ./logs/test/$dfn

ps -ef | grep pidstat* | grep -v grep | awk '{print $2}' >> ./logs/test/$dfn

while read line
do
kill -9 $line
echo $line
done < ./logs/test/$dfn

rm ./logs/test/$dfn

exit 0

