#!/bin/bash

testdir=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir

#nohup ./test_feed_dummy 1 test &

#values below are for 2 hrs periods
nohup ./test_feed1 21 $testdir &
sleep 5

nohup ./test_feed2 42 $testdir &

sleep 5

nohup ./test_feed3_nogzip 21 $testdir &
sleep 5

#for feed 4-6 need to change number of files to break out of loop for shorter duration tests
nohup ./test_feed4 1 $testdir &
#sleep 1


#nohup ./test_feed5 1 $testdir &
#sleep 1

#nohup ./test_feed6 2 $testdir &

#nohup ./test_feed7 20 $testdir &


#nohup ./test_feed8 2 $testdir &

#nohup ./test_feed9 134 $testdir &


#nohup ./test_feed10 834 $testdir &
#sleep 1


exit

