#!/bin/bash

testdir=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir

sleep 5
#start pidstat monitoring
nohup ./collect_all 300 $testdir &


nohup ./test_awsv 300 $testdir &
sleep 5

#values below are for 5 hrs periods
nohup ./test_feed1 300 $testdir &
sleep 5

nohup ./test_feed2 300 $testdir &

sleep 5

nohup ./test_feed3 300 $testdir &
sleep 5

#for feed 4-6 need to change number of files to break out of loop for shorter duration tests
nohup ./test_feed4 300 $testdir &
sleep 5


nohup ./test_feed5 300 $testdir &
sleep 5

nohup ./test_feed6 300 $testdir &

#nohup ./test_feed7 20 $testdir &


#nohup ./test_feed8 2 $testdir &

#nohup ./test_feed9 134 $testdir &


#nohup ./test_feed10 834 $testdir &
#sleep 1


exit

