#!/bin/bash

testdir=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")

mkdir ./logs/$testdir

nohup ./test_awsv 6000 $testdir &
sleep 5

#values below are for 100 hrs periods
nohup ./test_feed1 6000 $testdir &
sleep 5

nohup ./test_feed2 6000 $testdir &

sleep 5

nohup ./test_feed3 6000 $testdir &
sleep 5


nohup ./test_feed4 6000 $testdir &
sleep 5


nohup ./test_feed5 6000 $testdir &
sleep 5

nohup ./test_feed6 6000 $testdir &

sleep 5

nohup ./test_feed7 6000 $testdir &

sleep 5

nohup ./test_feed8 6000 $testdir &

sleep 5
nohup ./test_feed9 6000 $testdir &

sleep 5

nohup ./test_feed10 6000 $testdir &
#sleep 1


exit

