#!/bin/bash

testdir=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir

#first parameter is test duration in minutes 1.5 hrs is 90 min
nohup ./test_awsv 120 $testdir &

sleep 14400

#=====================================================

testdir1=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir1

nohup ./test_feed1 120 $testdir1 &

sleep 14400
#=====================================================

testdir2=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir2

nohup ./test_feed2 120 $testdir2 &

sleep 14400

#======================================================
testdir3=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir3


nohup ./test_feed3 120 $testdir3 &
sleep 14400


#=====================================================
testdir4=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir4

nohup ./test_feed4 120 $testdir4 &

sleep 14400

./start_test_feed1_2_3_4_awsv_5hrs &
#nohup ./test_feed5 90 $testdir &
#sleep 1

#nohup ./test_feed6 90 $testdir &

#nohup ./test_feed7 90 $testdir &


#nohup ./test_feed8 90 $testdir &

#nohup ./test_feed9 90 $testdir &


#nohup ./test_feed10 90 $testdir &
#sleep 1


exit

