#!/bin/bash

testdir=$(printf "%s_%s" "TEST" "$(date +%m%d%H%M%S)")
mkdir ./logs/$testdir

nohup ./test_awsv 300 $testdir &
sleep 5

#values below are for 5 hrs periods
nohup ./test_feed1 300 $testdir &
sleep 5

nohup ./test_feed2 300 $testdir &

sleep 5

nohup ./test_feed3 300 $testdir &
sleep 5


nohup ./test_feed4 300 $testdir &
sleep 5


nohup ./test_feed5 300 $testdir &
sleep 5

nohup ./test_feed6 300 $testdir &

sleep 5

nohup ./test_feed7 300 $testdir &

sleep 5

nohup ./test_feed8 300 $testdir &

sleep 5
nohup ./test_feed9 300 $testdir &

sleep 5

nohup ./test_feed10 300 $testdir &
#sleep 1


exit

